/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screens;

import Files.reservationFile;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import models.Movie;
import models.Reservation;

/**
 *
 * @author lenovo gaming3
 */
public class Booking extends JFrame implements ActionListener {

    static Movie movie;
    static String movieName;
    // array of selected seats
    private ArrayList<String> selectedSeats = new ArrayList<>();

    // Keeps track of seats by name
    private Map<String, JButton> seatButtonMap = new HashMap<>();

    /**
     * Creates new form Booking
     */
    public Booking(Movie movie) {
        this.movie = movie;
        initComponents();
        this.setTitle("Booking");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        movieTime.addActionListener(this);
        this.movieName = movie.getTitle();
        movName.setText("Movie: " + movieName);

        // Initialize button list
        initializeSeatButtons();
        //get the reserved seats
        getReservedSeats();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        numOfSeats = new javax.swing.JLabel();
        bookBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        reservationName = new javax.swing.JLabel();
        movieTime = new javax.swing.JComboBox<>();
        NoOfSeats3 = new javax.swing.JRadioButton();
        NoOfSeats2 = new javax.swing.JRadioButton();
        NoOfSeats1 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        ReservName = new javax.swing.JTextField();
        movName = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        available = new javax.swing.JLabel();
        white = new javax.swing.JLabel();
        red = new javax.swing.JLabel();
        Booked = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        C1 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        A6 = new javax.swing.JButton();
        A3 = new javax.swing.JButton();
        A1 = new javax.swing.JButton();
        A2 = new javax.swing.JButton();
        C2 = new javax.swing.JButton();
        C6 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        A5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        A4 = new javax.swing.JButton();
        C4 = new javax.swing.JButton();
        C5 = new javax.swing.JButton();
        C3 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        selected1 = new javax.swing.JLabel();
        green = new javax.swing.JLabel();
        selectSeat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 87));

        bookBtn.setBackground(new java.awt.Color(255, 0, 0));
        bookBtn.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        bookBtn.setForeground(new java.awt.Color(255, 204, 87));
        bookBtn.setText("Book Seat");
        bookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Time:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Reservation Name");

        movieTime.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        movieTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "18:00", "21:00", "00:00" }));

        buttonGroup1.add(NoOfSeats3);
        NoOfSeats3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NoOfSeats3.setText("3");

        buttonGroup1.add(NoOfSeats2);
        NoOfSeats2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NoOfSeats2.setText("2");

        buttonGroup1.add(NoOfSeats1);
        NoOfSeats1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NoOfSeats1.setSelected(true);
        NoOfSeats1.setText("1");
        NoOfSeats1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoOfSeats1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("No.of seats:");

        movName.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        movName.setText("Movie: movie title");

        home.setBackground(new java.awt.Color(255, 0, 0));
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/navigation/home.png"))); // NOI18N
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(255, 0, 0));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/navigation/back.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(NoOfSeats1)
                                                .addGap(67, 67, 67)
                                                .addComponent(NoOfSeats2)
                                                .addGap(73, 73, 73)
                                                .addComponent(NoOfSeats3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(ReservName, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(86, 86, 86))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(movName, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(movieTime, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numOfSeats, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(reservationName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(reservationName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(numOfSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(movName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ReservName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(movieTime, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoOfSeats3)
                    .addComponent(NoOfSeats2)
                    .addComponent(NoOfSeats1))
                .addGap(58, 58, 58)
                .addComponent(bookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 87));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        available.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        available.setText("Available");
        jPanel2.add(available, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 60, 30));

        white.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        white.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seats/white.png"))); // NOI18N
        jPanel2.add(white, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 30, 30));

        red.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        red.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seats/red.png"))); // NOI18N
        jPanel2.add(red, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, 20, 30));

        Booked.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Booked.setText("Booked");
        jPanel2.add(Booked, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 60, 30));

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setPreferredSize(new java.awt.Dimension(700, 200));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("A");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 30, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("B");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 30, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("C");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 40, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("1");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 40, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("2");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 20, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("3");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 20, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("4");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 30, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("5");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 40, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("6");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 40, 30));

        C1.setBackground(new java.awt.Color(51, 51, 51));
        C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seats/availableSeat.png"))); // NOI18N
        C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1ActionPerformed(evt);
            }
        });
        jPanel3.add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 50, 50));

        B5.setBackground(new java.awt.Color(51, 51, 51));
        B5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seats/availableSeat.png"))); // NOI18N
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });
        jPanel3.add(B5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 50, 50));

        B1.setBackground(new java.awt.Color(51, 51, 51));
        B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seats/availableSeat.png"))); // NOI18N
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        jPanel3.add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 50, 50));

        A6.setBackground(new java.awt.Color(51, 51, 51));
        A6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seats/availableSeat.png"))); // NOI18N
        A6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A6ActionPerformed(evt);
            }
        });
        jPanel3.add(A6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 50, 50));

        A3.setBackground(new java.awt.Color(51, 51, 51));
        A3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seats/availableSeat.png"))); // NOI18N
        A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3ActionPerformed(evt);
            }
        });
        jPanel3.add(A3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 50, 50));

        A1.setBackground(new java.awt.Color(51, 51, 51));
        A1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seats/availableSeat.png"))); // NOI18N
        A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1ActionPerformed(evt);
            }
        });
        jPanel3.add(A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 50, 50));

        A2.setBackground(new java.awt.Color(51, 51, 51));
        A2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seats/availableSeat.png"))); // NOI18N
        A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2ActionPerformed(evt);
            }
        });
        jPanel3.add(A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 50, 50));

        C2.setBackground(new java.awt.Color(51, 51, 51));
        C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seats/availableSeat.png"))); // NOI18N
        C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C2ActionPerformed(evt);
            }
        });
        jPanel3.add(C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 50, 50));

        C6.setBackground(new java.awt.Color(51, 51, 51));
        C6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seats/availableSeat.png"))); // NOI18N
        C6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C6ActionPerformed(evt);
            }
        });
        jPanel3.add(C6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 50, 50));

        B4.setBackground(new java.awt.Color(51, 51, 51));
        B4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seats/availableSeat.png"))); // NOI18N
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });
        jPanel3.add(B4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 50, 50));

        A5.setBackground(new java.awt.Color(51, 51, 51));
        A5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seats/availableSeat.png"))); // NOI18N
        A5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A5ActionPerformed(evt);
            }
        });
        jPanel3.add(A5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 50, 50));

        B6.setBackground(new java.awt.Color(51, 51, 51));
        B6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seats/availableSeat.png"))); // NOI18N
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });
        jPanel3.add(B6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 50, 50));

        A4.setBackground(new java.awt.Color(51, 51, 51));
        A4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seats/availableSeat.png"))); // NOI18N
        A4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A4ActionPerformed(evt);
            }
        });
        jPanel3.add(A4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 50, 50));

        C4.setBackground(new java.awt.Color(51, 51, 51));
        C4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seats/availableSeat.png"))); // NOI18N
        C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C4ActionPerformed(evt);
            }
        });
        jPanel3.add(C4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 50, 50));

        C5.setBackground(new java.awt.Color(51, 51, 51));
        C5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seats/availableSeat.png"))); // NOI18N
        C5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C5ActionPerformed(evt);
            }
        });
        jPanel3.add(C5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 50, 50));

        C3.setBackground(new java.awt.Color(51, 51, 51));
        C3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seats/availableSeat.png"))); // NOI18N
        C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C3ActionPerformed(evt);
            }
        });
        jPanel3.add(C3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 50, 50));

        B3.setBackground(new java.awt.Color(51, 51, 51));
        B3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seats/availableSeat.png"))); // NOI18N
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });
        jPanel3.add(B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 50, 50));

        B2.setBackground(new java.awt.Color(51, 51, 51));
        B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seats/availableSeat.png"))); // NOI18N
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });
        jPanel3.add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 50, 50));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 670, 290));

        selected1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        selected1.setText("Selected");
        jPanel2.add(selected1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, 30));

        green.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        green.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seats/green.png"))); // NOI18N
        jPanel2.add(green, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 10, 30));

        selectSeat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selectSeat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/curtains.png"))); // NOI18N
        jPanel2.add(selectSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1020, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NoOfSeats1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoOfSeats1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoOfSeats1ActionPerformed

    private void A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1ActionPerformed
        seatButtonClicked(A1, "A1");
    }//GEN-LAST:event_A1ActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
        seatButtonClicked(B1, "B1");
    }//GEN-LAST:event_B1ActionPerformed

    private void A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2ActionPerformed
        // TODO add your handling code here:
        seatButtonClicked(A2, "A2");
    }//GEN-LAST:event_A2ActionPerformed

    private void bookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookBtnActionPerformed

        String customername = ReservName.getText();
        String showtime = (String) movieTime.getSelectedItem();
        if (customername.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter reservation name!");
        } else if (selectedSeats.size() != getMaxSeats()) {
            JOptionPane.showMessageDialog(this, "Please select the desired seat!");
        } else {
            Reservation res = new Reservation(movieName, showtime, customername, selectedSeats);
            if (res.processBooking()) {
                ReservName.setText("");
                movieTime.setSelectedIndex(0);
                NoOfSeats1.setSelected(true);

                confirmationScreen confirm = new confirmationScreen(selectedSeats);
                confirm.setVisible(true);
                confirm.setLocationRelativeTo(null);
                //after confirming make the selected seats as reserved
                getReservedSeats();
            }
        }
    }//GEN-LAST:event_bookBtnActionPerformed

    private void A3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3ActionPerformed
        // TODO add your handling code here:
        seatButtonClicked(A3, "A3");
    }//GEN-LAST:event_A3ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        // TODO add your handling code here:
        seatButtonClicked(B2, "B2");
    }//GEN-LAST:event_B2ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        // TODO add your handling code here:
        seatButtonClicked(B3, "B3");
    }//GEN-LAST:event_B3ActionPerformed

    private void C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1ActionPerformed
        // TODO add your handling code here:
        seatButtonClicked(C1, "C1");
    }//GEN-LAST:event_C1ActionPerformed

    private void C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C2ActionPerformed
        // TODO add your handling code here:
        seatButtonClicked(C2, "C2");
    }//GEN-LAST:event_C2ActionPerformed

    private void C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C3ActionPerformed
        // TODO add your handling code here:
        seatButtonClicked(C3, "C3");
    }//GEN-LAST:event_C3ActionPerformed

    private void A4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A4ActionPerformed
        // TODO add your handling code here:
        seatButtonClicked(A4, "A4");
    }//GEN-LAST:event_A4ActionPerformed

    private void A5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A5ActionPerformed
        // TODO add your handling code here:
        seatButtonClicked(A5, "A5");
    }//GEN-LAST:event_A5ActionPerformed

    private void A6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A6ActionPerformed
        // TODO add your handling code here:
        seatButtonClicked(A6, "A6");
    }//GEN-LAST:event_A6ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        // TODO add your handling code here:
        seatButtonClicked(B4, "B4");
    }//GEN-LAST:event_B4ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        // TODO add your handling code here:
        seatButtonClicked(B5, "B5");

    }//GEN-LAST:event_B5ActionPerformed

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
        // TODO add your handling code here:
        seatButtonClicked(B6, "B6");
    }//GEN-LAST:event_B6ActionPerformed

    private void C4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C4ActionPerformed
        // TODO add your handling code here:
        seatButtonClicked(C4, "C4");
    }//GEN-LAST:event_C4ActionPerformed

    private void C5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C5ActionPerformed
        // TODO add your handling code here:
        seatButtonClicked(C5, "C5");
    }//GEN-LAST:event_C5ActionPerformed

    private void C6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C6ActionPerformed
        // TODO add your handling code here:
        seatButtonClicked(C6, "C6");
    }//GEN-LAST:event_C6ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Details details = new Details(movie);
        this.setVisible(false);
        details.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        Home_Screen home = new Home_Screen();
        this.setVisible(false);
        home.setVisible(true);
    }//GEN-LAST:event_homeActionPerformed

    @Override
    public void actionPerformed(ActionEvent e) {
        String time = (String) movieTime.getSelectedItem();
        if (e.getSource() == movieTime) {
            if (time.equals("18:00")) {
                removeSelected();
                makeAllSeatsAvailable();
                getReservedSeats();
            } else if (time.equals("21:00")) {
                removeSelected();
                makeAllSeatsAvailable();
                getReservedSeats();
            } else if (time.equals("00:00")) {
                removeSelected();
                makeAllSeatsAvailable();
                getReservedSeats();
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking(Booking.movie).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A1;
    private javax.swing.JButton A2;
    private javax.swing.JButton A3;
    private javax.swing.JButton A4;
    private javax.swing.JButton A5;
    private javax.swing.JButton A6;
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JLabel Booked;
    private javax.swing.JButton C1;
    private javax.swing.JButton C2;
    private javax.swing.JButton C3;
    private javax.swing.JButton C4;
    private javax.swing.JButton C5;
    private javax.swing.JButton C6;
    private javax.swing.JRadioButton NoOfSeats1;
    private javax.swing.JRadioButton NoOfSeats2;
    private javax.swing.JRadioButton NoOfSeats3;
    private javax.swing.JTextField ReservName;
    private javax.swing.JLabel available;
    private javax.swing.JButton back;
    private javax.swing.JButton bookBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel green;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel movName;
    private javax.swing.JComboBox<String> movieTime;
    private javax.swing.JLabel numOfSeats;
    private javax.swing.JLabel red;
    private javax.swing.JLabel reservationName;
    private javax.swing.JLabel selectSeat;
    private javax.swing.JLabel selected1;
    private javax.swing.JLabel white;
    // End of variables declaration//GEN-END:variables

    private void initializeSeatButtons() {
        // Add all seat buttons to the list
        seatButtonMap.put("A1", A1);
        seatButtonMap.put("A2", A2);
        seatButtonMap.put("A3", A3);
        seatButtonMap.put("A4", A4);
        seatButtonMap.put("A5", A5);
        seatButtonMap.put("A6", A6);

        seatButtonMap.put("B1", B1);
        seatButtonMap.put("B2", B2);
        seatButtonMap.put("B3", B3);
        seatButtonMap.put("B4", B4);
        seatButtonMap.put("B5", B5);
        seatButtonMap.put("B6", B6);

        seatButtonMap.put("C1", C1);
        seatButtonMap.put("C2", C2);
        seatButtonMap.put("C3", C3);
        seatButtonMap.put("C4", C4);
        seatButtonMap.put("C5", C5);
        seatButtonMap.put("C6", C6);
    }

    private void getReservedSeats() {
        //get the selected time
        String time = (String) movieTime.getSelectedItem();
        ArrayList<String> reservedSeats = reservationFile.getReservedSeats(movieName, time);
        // Update icons for reserved seats
        for (String seat : reservedSeats) {
            JButton seatButton = findButtonByName(seat);
            if (seatButton != null) {
                updateSeatIcon(seatButton, "reserved");
            }
        }
    }

    private JButton findButtonByName(String seatName) {
        // Retrieve the button directly from the map
        return seatButtonMap.get(seatName);
    }

    private void makeAllSeatsAvailable() {
        // Iterate through each entry in the seatButtonMap
        for (Map.Entry<String, JButton> entry : seatButtonMap.entrySet()) {
            JButton seatButton = entry.getValue();
            updateSeatIcon(seatButton, "available"); // Set each button to "available"
        }
    }

    private void seatButtonClicked(JButton seatButton, String buttonName) {
        if (seatButton.getIcon().toString().contains("reservedSeat.png")) {
            return;
        }
        int maxSeats = getMaxSeats(); // Get the maximum number of seats allowed based on the selected radio button

        if (!selectedSeats.contains(buttonName)) {
            if (selectedSeats.size() < maxSeats) {
                selectedSeats.add(buttonName);
                updateSeatIcon(seatButton, "selected");
                System.out.println(selectedSeats);
            } else {
                
                System.out.println("Maximum number of seats selected!");
            }
        } else {
            selectedSeats.remove(buttonName);
            updateSeatIcon(seatButton, "available");
            System.out.println("after remove" + selectedSeats);
        }
    }

    private void removeSelected() {
        selectedSeats.clear();
    }

    private int getMaxSeats() {
        if (NoOfSeats1.isSelected()) {
            return 1;
        } else if (NoOfSeats2.isSelected()) {
            return 2;
        } else if (NoOfSeats3.isSelected()) {
            return 3;
        }
        return 1; // Default to 1 if no radio button is selected
    }

    private void updateSeatIcon(JButton seatButton, String state) {
        // updates the icon of the seatButton based on its state (selected, available, or unavailable)
        switch (state) {
            case "selected":
                seatButton.setIcon(new ImageIcon("src\\seats\\selectedSeat.png"));
                break;
            case "available":
                seatButton.setIcon(new ImageIcon("src\\seats\\availableSeat.png"));
                break;
            case "reserved":
                seatButton.setIcon(new ImageIcon("src\\seats\\reservedSeat.png"));
                break;
            default:
                seatButton.setIcon(new ImageIcon("src\\seats\\availableSeat.png"));
        }
    }
}
