package Screens;

import Consts.AppStrings;
import Files.reservationFile;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import models.Movie;

/**
 *
 * @author T-Man
 */
public class Details extends javax.swing.JFrame {

    Movie movie;

    /**
     * Creates new form Interstellar_Details
     */
    public Details(Movie movie) {
        initComponents();
        this.setTitle("Moive Details");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.movie = movie;
        Image.setIcon(movie.getThumpnail());
        movieName.setText(movie.getTitle());
        movieCategory.setText(movie.getCategory());
        movieDisc.setText(movie.getDiscription());
        movieDisc.setEditable(false);
        getCrowdedTime(movie.getTitle());
        getNoOfReservedSeats(movie.getTitle());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        movieDisc = new javax.swing.JTextArea();
        Image = new javax.swing.JLabel();
        movieCategory = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        movieName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mostCrowdedTime = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        numberOfSeatsSold = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 87));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtn.setBackground(new java.awt.Color(255, 0, 0));
        backBtn.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/navigation/back.png"))); // NOI18N
        backBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 40, 40));

        movieDisc.setBackground(new java.awt.Color(255, 204, 87));
        movieDisc.setColumns(20);
        movieDisc.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        movieDisc.setLineWrap(true);
        movieDisc.setRows(5);
        movieDisc.setText(" bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla   ");
        movieDisc.setWrapStyleWord(true);
        movieDisc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        movieDisc.setPreferredSize(new java.awt.Dimension(350, 131));
        jPanel1.add(movieDisc, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 370, 290));

        Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgDetail/interstellar.png"))); // NOI18N
        Image.setPreferredSize(new java.awt.Dimension(0, 900));
        jPanel1.add(Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -20, 450, 860));

        movieCategory.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        movieCategory.setText("movieCategory");
        movieCategory.setToolTipText("");
        jPanel1.add(movieCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 390, 50));

        jButton4.setBackground(new java.awt.Color(255, 0, 51));
        jButton4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 204, 87));
        jButton4.setText("BOOK NOW");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 750, 180, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel2.setText("Most CROWDED TIME:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 590, 370, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel3.setText("MOVIE CATEGORY:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 230, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel5.setText("MOVIE NAME:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 230, 40));

        movieName.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        movieName.setText("movieName");
        movieName.setToolTipText("");
        jPanel1.add(movieName, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 390, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel4.setText("MOVIE SEATS SOLD:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 660, 370, 40));

        mostCrowdedTime.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        mostCrowdedTime.setText("18.00, or 21.00, or 00.00 ");
        jPanel1.add(mostCrowdedTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 620, 380, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel6.setText("MOVIE TIMES:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, 370, 40));

        numberOfSeatsSold.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        numberOfSeatsSold.setText("no.of sold seats");
        jPanel1.add(numberOfSeatsSold, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 700, 360, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel7.setText("MOVIE DISCRITPTION:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 370, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel1.setText("18.00, 21.00, 00.00 ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 560, 340, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        Home_Screen home = new Home_Screen();
        this.setVisible(false);
        home.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Booking booking = new Booking(movie);
        this.setVisible(false);
        booking.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    //numberOfSeatsSold
    public void getNoOfReservedSeats(String movieTitle) {
        ArrayList<String> Rseats = reservationFile.getNoOfSoldSeats(movieTitle);
        numberOfSeatsSold.setText("" + Rseats.size() + " seats");
    }

    public void getCrowdedTime(String movieTitle) {
        ArrayList<String> Rseats6 = reservationFile.getReservedSeats(movieTitle, "18:00");
        ArrayList<String> Rseats9 = reservationFile.getReservedSeats(movieTitle, "21:00");
        ArrayList<String> Rseats12 = reservationFile.getReservedSeats(movieTitle, "00:00");

        // Check if all time slots have no reserved seats
        if (Rseats6.isEmpty() && Rseats9.isEmpty() && Rseats12.isEmpty()) {
            mostCrowdedTime.setText("No reservations available for any showtime.");
        } else {
            String crowdedTime = getMax(Rseats6, Rseats9, Rseats12);
            mostCrowdedTime.setText(crowdedTime);
        }
    }

    public String getMax(ArrayList<String> one, ArrayList<String> two, ArrayList<String> three) {
        int max = one.size();
        String time = "18:00";

        if (two.size() > max) {
            max = two.size();
            time = "21:00";
        }

        if (three.size() > max) {
            max = three.size();
            time = "00:00";
        }

        return time;
    }

    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ImageIcon img = new ImageIcon("src\\imgDetail\\imitation game.png");
                Movie interstellar = new Movie(AppStrings.nameOfFilm2, AppStrings.DescOfFilm2, AppStrings.scientific, img, AppStrings.durationOfFilm2);
                new Details(interstellar).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Image;
    private javax.swing.JButton backBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mostCrowdedTime;
    private javax.swing.JLabel movieCategory;
    private javax.swing.JTextArea movieDisc;
    private javax.swing.JLabel movieName;
    private javax.swing.JLabel numberOfSeatsSold;
    // End of variables declaration//GEN-END:variables
}
