/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screens;

import Consts.AppStrings;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import models.Movie;

/*
 * @author lenovo gaming3
*/

public class Home_Screen extends JFrame implements ActionListener {
 
    /**
     * Creates new form Home_Screen
     */
    public Home_Screen() {
        initComponents();
        this.setTitle("Home Screen");
        this.setSize(600, 800);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        jComboBox1.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<String>();
        moviesPanel = new javax.swing.JPanel();
        johnRamboBtn = new javax.swing.JButton();
        hallPassBtn = new javax.swing.JButton();
        dumpNdumperBtn = new javax.swing.JButton();
        interstellarBtn = new javax.swing.JButton();
        fridayBtn = new javax.swing.JButton();
        anihilationBtn = new javax.swing.JButton();
        theImitationBtn = new javax.swing.JButton();
        realHeroBtn = new javax.swing.JButton();
        johnWickBtn = new javax.swing.JButton();
        madMaxBtn = new javax.swing.JButton();
        fastNfuriosBtn = new javax.swing.JButton();
        theMartionBtn = new javax.swing.JButton();
        user = new javax.swing.JButton();
        home = new javax.swing.JButton();

        jButton7.setText("jButton7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 800));

        jPanel1.setBackground(new java.awt.Color(231, 39, 52));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 87));
        jLabel2.setText("Movie Ticket Reservation");

        jPanel2.setBackground(new java.awt.Color(255, 204, 87));
        jPanel2.setPreferredSize(new java.awt.Dimension(630, 3140));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("Movie Categroies:");

        jComboBox1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ALL", "ACTION", "COMEDY", "SCIENTIFIC" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        moviesPanel.setBackground(new java.awt.Color(255, 204, 87));
        moviesPanel.setLayout(new java.awt.CardLayout());

        johnRamboBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/john rambo.jpeg"))); // NOI18N
        johnRamboBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                johnRamboBtnActionPerformed(evt);
            }
        });

        hallPassBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/HALL PASS.jpeg"))); // NOI18N
        hallPassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hallPassBtnActionPerformed(evt);
            }
        });

        dumpNdumperBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/dump and dumper.jpeg"))); // NOI18N
        dumpNdumperBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dumpNdumperBtnActionPerformed(evt);
            }
        });

        interstellarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/interstealer.jpeg"))); // NOI18N
        interstellarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interstellarBtnActionPerformed(evt);
            }
        });

        fridayBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/friday.jpeg"))); // NOI18N
        fridayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fridayBtnActionPerformed(evt);
            }
        });

        anihilationBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/anihilation game.jpeg"))); // NOI18N
        anihilationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anihilationBtnActionPerformed(evt);
            }
        });

        theImitationBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/the imitation game.jpeg"))); // NOI18N
        theImitationBtn.setPreferredSize(new java.awt.Dimension(283, 309));
        theImitationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                theImitationBtnActionPerformed(evt);
            }
        });

        realHeroBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/real hero.jpeg"))); // NOI18N
        realHeroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realHeroBtnActionPerformed(evt);
            }
        });

        johnWickBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/john wick.jpeg"))); // NOI18N
        johnWickBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                johnWickBtnActionPerformed(evt);
            }
        });

        madMaxBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/mad max (2).png"))); // NOI18N
        madMaxBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                madMaxBtnActionPerformed(evt);
            }
        });

        fastNfuriosBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/fast&furios.jpeg"))); // NOI18N
        fastNfuriosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fastNfuriosBtnActionPerformed(evt);
            }
        });

        theMartionBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/the martian.jpeg"))); // NOI18N
        theMartionBtn.setPreferredSize(new java.awt.Dimension(283, 309));
        theMartionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                theMartionBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(dumpNdumperBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(interstellarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(theImitationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                        .addGap(45, 45, 45))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(27, 27, 27)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fridayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(johnRamboBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(theMartionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(90, 90, 90)
                                .addComponent(moviesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(hallPassBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(realHeroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(johnWickBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(madMaxBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(anihilationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fastNfuriosBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(99, 99, 99))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(johnRamboBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dumpNdumperBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fridayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(moviesPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(interstellarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(theImitationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(theMartionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fastNfuriosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hallPassBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(madMaxBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(realHeroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(johnWickBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anihilationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1106, Short.MAX_VALUE))
        );

        interstellarBtn.getAccessibleContext().setAccessibleName("InterBtn ");
        interstellarBtn.getAccessibleContext().setAccessibleDescription("");
        anihilationBtn.getAccessibleContext().setAccessibleName("interStallerBtn");

        jScrollPane1.setViewportView(jPanel2);

        user.setBackground(new java.awt.Color(231, 39, 52));
        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/navigation/Logout.png"))); // NOI18N
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });

        home.setBackground(new java.awt.Color(231, 39, 52));
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/navigation/menu.png"))); // NOI18N
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(95, 95, 95)
                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 2058, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void theImitationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theImitationBtnActionPerformed
        ImageIcon img = new ImageIcon("src\\imgDetail\\imitation game.png");
        Movie movie = new Movie(AppStrings.nameOfFilm11, AppStrings.DescOfFilm11, AppStrings.scientific, img, AppStrings.durationOfFilm11);

        Details details = new Details(movie);
        this.setVisible(false);
        details.setVisible(true);
    }//GEN-LAST:event_theImitationBtnActionPerformed

    private void interstellarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interstellarBtnActionPerformed
        ImageIcon img = new ImageIcon("src\\imgDetail\\interstellar.png");
        Movie movie = new Movie(AppStrings.nameOfFilm1, AppStrings.DescOfFilm1, AppStrings.scientific, img, AppStrings.durationOfFilm1);

        Details details = new Details(movie);
        this.setVisible(false);
        details.setVisible(true);
    }//GEN-LAST:event_interstellarBtnActionPerformed

    private void anihilationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anihilationBtnActionPerformed
        ImageIcon img = new ImageIcon("src\\imgDetail\\anihilation.png");
        Movie movie = new Movie(AppStrings.nameOfFilm2, AppStrings.DescOfFilm2, AppStrings.scientific, img, AppStrings.durationOfFilm2);

        Details details = new Details(movie);
        this.setVisible(false);
        details.setVisible(true);
    }//GEN-LAST:event_anihilationBtnActionPerformed

    private void realHeroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realHeroBtnActionPerformed
        ImageIcon img = new ImageIcon("src\\imgDetail\\real hero.png");
        Movie movie = new Movie(AppStrings.nameOfFilm3, AppStrings.DescOfFilm3, AppStrings.comady, img, AppStrings.durationOfFilm3);

        Details details = new Details(movie);
        this.setVisible(false);
        details.setVisible(true);
    }//GEN-LAST:event_realHeroBtnActionPerformed

    private void madMaxBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_madMaxBtnActionPerformed
        ImageIcon img = new ImageIcon("src\\imgDetail\\mad max.png");
        Movie movie = new Movie(AppStrings.nameOfFilm4, AppStrings.DescOfFilm4, AppStrings.action, img, AppStrings.durationOfFilm4);

        Details details = new Details(movie);
        this.setVisible(false);
        details.setVisible(true);
    }//GEN-LAST:event_madMaxBtnActionPerformed

    private void fridayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fridayBtnActionPerformed
        ImageIcon img = new ImageIcon("src\\imgDetail\\friday.png");
        Movie movie = new Movie(AppStrings.nameOfFilm5, AppStrings.DescOfFilm5, AppStrings.comady, img, AppStrings.durationOfFilm5);

        Details details = new Details(movie);
        this.setVisible(false);
        details.setVisible(true);
    }//GEN-LAST:event_fridayBtnActionPerformed

    private void theMartionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theMartionBtnActionPerformed
        ImageIcon img = new ImageIcon("src\\imgDetail\\the martion.png");
        Movie movie = new Movie(AppStrings.nameOfFilm6, AppStrings.DescOfFilm6, AppStrings.scientific, img, AppStrings.durationOfFilm6);

        Details details = new Details(movie);
        this.setVisible(false);
        details.setVisible(true);
    }//GEN-LAST:event_theMartionBtnActionPerformed

    private void johnWickBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_johnWickBtnActionPerformed
        ImageIcon img = new ImageIcon("src\\imgDetail\\john wick.png");
        Movie movie = new Movie(AppStrings.nameOfFilm12, AppStrings.DescOfFilm12, AppStrings.action, img, AppStrings.durationOfFilm12);

        Details details = new Details(movie);
        this.setVisible(false);
        details.setVisible(true);
    }//GEN-LAST:event_johnWickBtnActionPerformed

    private void hallPassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hallPassBtnActionPerformed
        ImageIcon img = new ImageIcon("src\\imgDetail\\hall pass.jpeg");
        Movie movie = new Movie(AppStrings.nameOfFilm7, AppStrings.DescOfFilm7, AppStrings.comady, img, AppStrings.durationOfFilm7);

        Details details = new Details(movie);
        this.setVisible(false);
        details.setVisible(true);
    }//GEN-LAST:event_hallPassBtnActionPerformed

    private void johnRamboBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_johnRamboBtnActionPerformed
        ImageIcon img = new ImageIcon("src\\imgDetail\\john rambo.png");
        Movie movie = new Movie(AppStrings.nameOfFilm8, AppStrings.DescOfFilm8, AppStrings.action, img, AppStrings.durationOfFilm8);

        Details details = new Details(movie);
        this.setVisible(false);
        details.setVisible(true);
    }//GEN-LAST:event_johnRamboBtnActionPerformed

    private void fastNfuriosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fastNfuriosBtnActionPerformed
        ImageIcon img = new ImageIcon("src\\imgDetail\\fastNfurois.png");
        Movie movie = new Movie(AppStrings.nameOfFilm9, AppStrings.DescOfFilm9, AppStrings.action, img, AppStrings.durationOfFilm9);

        Details details = new Details(movie);
        this.setVisible(false);
        details.setVisible(true);
    }//GEN-LAST:event_fastNfuriosBtnActionPerformed

    private void dumpNdumperBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dumpNdumperBtnActionPerformed
        ImageIcon img = new ImageIcon("src\\imgDetail\\dumpNdumper.png");
        Movie movie = new Movie(AppStrings.nameOfFilm10, AppStrings.DescOfFilm10, AppStrings.comady, img, AppStrings.durationOfFilm10);

        Details details = new Details(movie);
        this.setVisible(false);
        details.setVisible(true);
    }//GEN-LAST:event_dumpNdumperBtnActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        int response = JOptionPane.showConfirmDialog(
                null,
                "Are you sure you want to logout and return to the login page?",
                "Confirm Logout",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (response == JOptionPane.YES_OPTION) {
            Login_Screen loginPage = new Login_Screen();
            loginPage.setVisible(true);
            dispose(); 
        }
    }//GEN-LAST:event_userActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        //nothing, we're on the same home page hehe
        this.setVisible(false);
        this.setVisible(true);
        jComboBox1.setSelectedIndex(0);
    }//GEN-LAST:event_homeActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anihilationBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton dumpNdumperBtn;
    private javax.swing.JButton fastNfuriosBtn;
    private javax.swing.JButton fridayBtn;
    private javax.swing.JButton hallPassBtn;
    private javax.swing.JButton home;
    private javax.swing.JButton interstellarBtn;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton johnRamboBtn;
    private javax.swing.JButton johnWickBtn;
    private javax.swing.JButton madMaxBtn;
    private javax.swing.JPanel moviesPanel;
    private javax.swing.JButton realHeroBtn;
    private javax.swing.JButton theImitationBtn;
    private javax.swing.JButton theMartionBtn;
    private javax.swing.JButton user;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        String category = (String) jComboBox1.getSelectedItem();
        if (e.getSource() == jComboBox1) {

            if (category.equals("ACTION")) {
                johnWickBtn.setVisible(true);
                madMaxBtn.setVisible(true);
                fastNfuriosBtn.setVisible(true);
                johnRamboBtn.setVisible(true);

                dumpNdumperBtn.setVisible(false);
                hallPassBtn.setVisible(false);
                realHeroBtn.setVisible(false);
                fridayBtn.setVisible(false);

                interstellarBtn.setVisible(false);
                anihilationBtn.setVisible(false);
                theImitationBtn.setVisible(false);
                theMartionBtn.setVisible(false);
            } else if (category.equals("COMEDY")) {
                dumpNdumperBtn.setVisible(true);
                hallPassBtn.setVisible(true);
                realHeroBtn.setVisible(true);
                fridayBtn.setVisible(true);

                johnWickBtn.setVisible(false);
                madMaxBtn.setVisible(false);
                fastNfuriosBtn.setVisible(false);
                johnRamboBtn.setVisible(false);

                interstellarBtn.setVisible(false);
                anihilationBtn.setVisible(false);
                theImitationBtn.setVisible(false);
                theMartionBtn.setVisible(false);
            } else if (category.equals("SCIENTIFIC")) {
                interstellarBtn.setVisible(true);
                anihilationBtn.setVisible(true);
                theImitationBtn.setVisible(true);
                theMartionBtn.setVisible(true);

                johnWickBtn.setVisible(false);
                madMaxBtn.setVisible(false);
                fastNfuriosBtn.setVisible(false);
                johnRamboBtn.setVisible(false);

                dumpNdumperBtn.setVisible(false);
                hallPassBtn.setVisible(false);
                realHeroBtn.setVisible(false);
                fridayBtn.setVisible(false);
            } else /*if (category.equals("ALL"))*/ {
                johnWickBtn.setVisible(true);
                madMaxBtn.setVisible(true);
                fastNfuriosBtn.setVisible(true);
                johnRamboBtn.setVisible(true);

                dumpNdumperBtn.setVisible(true);
                hallPassBtn.setVisible(true);
                realHeroBtn.setVisible(true);
                fridayBtn.setVisible(true);

                interstellarBtn.setVisible(true);
                anihilationBtn.setVisible(true);
                theImitationBtn.setVisible(true);
                theMartionBtn.setVisible(true);
            }
        }
    }
}
